import Head from 'next/head';
import { Inter } from '@next/font/google';
import { Footer, Navbar } from '../components/Layout';
import { Button } from '../components/Button';
import Image from 'next/image';
import Hero from '../sections/Hero';
import About from '../sections/About';
import Projects from '../sections/Projects';
import Contact from '../sections/Contact';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Hridoy</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <main className={inter.className} id="home">
                <Navbar />
                <Hero />
                <About />
                <Projects />
                <Contact />
                <Footer />
            </main>
        </>
    );
}
