import Head from 'next/head';
import { Inter } from '@next/font/google';
import { Navbar } from '../components/Layout';
import { Button } from '../components/Button';
import Image from 'next/image';
import Hero from '../sections/Hero';
import About from '../sections/About';
import Projects from '../sections/Projects';
import Contact from '../sections/Contact';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={inter.className}>
                {/* navbar */}
                <Navbar />
                {/* hero section */}
                <Hero />
                {/* about section */}
                <About />
                {/* projects section */}
                <Projects />

                {/* contact section */}
                <Contact />

                {/* footer */}
                <footer className=" border-t border-gray-600 border-dashed text-white py-8">
                    <div className="container mx-auto px-4">
                        <div className="flex flex-col md:flex-row justify-between items-center">
                            <div className="flex items-center">
                                <div className="flex flex-col">
                                    <span className="text-sm">© 2022</span>
                                    <span className="text-sm">All rights reserved</span>
                                </div>
                            </div>
                            <div className="flex items-center">
                                <span className="text-sm">Made with </span>
                                <span className="relative px-2">
                                    <span className="w-10 h-10 bg-red-500 blur-[100px] absolute block" />
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="16"
                                        height="16"
                                        fill="currentColor"
                                        viewBox="0 0 16 16"
                                    >
                                        <path
                                            fillRule="evenodd"
                                            d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                        />
                                    </svg>
                                </span>
                                <span className="text-sm">by</span>
                                <a href="#" className="text-sm font-bold mx-2 hover:text-gray-300">
                                    @hridoy
                                </a>
                            </div>
                        </div>
                    </div>
                </footer>
            </main>
        </>
    );
}
